// Mapping between frontend key codes (KeyboardEvent.code-ish, see utils/keys.ts)
// and Linux evdev `Key` values.

#![cfg(target_os = "linux")]

use evdev::Key;

pub fn code_to_key(code: &str) -> Option<Key> {
    Some(match code {
        // Letters
        "KeyA" => Key::KEY_A,
        "KeyB" => Key::KEY_B,
        "KeyC" => Key::KEY_C,
        "KeyD" => Key::KEY_D,
        "KeyE" => Key::KEY_E,
        "KeyF" => Key::KEY_F,
        "KeyG" => Key::KEY_G,
        "KeyH" => Key::KEY_H,
        "KeyI" => Key::KEY_I,
        "KeyJ" => Key::KEY_J,
        "KeyK" => Key::KEY_K,
        "KeyL" => Key::KEY_L,
        "KeyM" => Key::KEY_M,
        "KeyN" => Key::KEY_N,
        "KeyO" => Key::KEY_O,
        "KeyP" => Key::KEY_P,
        "KeyQ" => Key::KEY_Q,
        "KeyR" => Key::KEY_R,
        "KeyS" => Key::KEY_S,
        "KeyT" => Key::KEY_T,
        "KeyU" => Key::KEY_U,
        "KeyV" => Key::KEY_V,
        "KeyW" => Key::KEY_W,
        "KeyX" => Key::KEY_X,
        "KeyY" => Key::KEY_Y,
        "KeyZ" => Key::KEY_Z,

        // Digits
        "Digit0" => Key::KEY_0,
        "Digit1" => Key::KEY_1,
        "Digit2" => Key::KEY_2,
        "Digit3" => Key::KEY_3,
        "Digit4" => Key::KEY_4,
        "Digit5" => Key::KEY_5,
        "Digit6" => Key::KEY_6,
        "Digit7" => Key::KEY_7,
        "Digit8" => Key::KEY_8,
        "Digit9" => Key::KEY_9,

        // F-row
        "F1" => Key::KEY_F1,
        "F2" => Key::KEY_F2,
        "F3" => Key::KEY_F3,
        "F4" => Key::KEY_F4,
        "F5" => Key::KEY_F5,
        "F6" => Key::KEY_F6,
        "F7" => Key::KEY_F7,
        "F8" => Key::KEY_F8,
        "F9" => Key::KEY_F9,
        "F10" => Key::KEY_F10,
        "F11" => Key::KEY_F11,
        "F12" => Key::KEY_F12,
        "F13" => Key::KEY_F13,
        "F14" => Key::KEY_F14,
        "F15" => Key::KEY_F15,
        "F16" => Key::KEY_F16,
        "F17" => Key::KEY_F17,
        "F18" => Key::KEY_F18,
        "F19" => Key::KEY_F19,
        "F20" => Key::KEY_F20,
        "F21" => Key::KEY_F21,
        "F22" => Key::KEY_F22,
        "F23" => Key::KEY_F23,
        "F24" => Key::KEY_F24,

        // Navigation / editing
        "Escape" => Key::KEY_ESC,
        "Tab" => Key::KEY_TAB,
        "CapsLock" => Key::KEY_CAPSLOCK,
        "Enter" => Key::KEY_ENTER,
        "Backspace" => Key::KEY_BACKSPACE,
        "Space" => Key::KEY_SPACE,
        "Delete" => Key::KEY_DELETE,
        "Insert" => Key::KEY_INSERT,
        "Home" => Key::KEY_HOME,
        "End" => Key::KEY_END,
        "PageUp" => Key::KEY_PAGEUP,
        "PageDown" => Key::KEY_PAGEDOWN,
        "ArrowLeft" => Key::KEY_LEFT,
        "ArrowRight" => Key::KEY_RIGHT,
        "ArrowUp" => Key::KEY_UP,
        "ArrowDown" => Key::KEY_DOWN,
        "PrintScreen" => Key::KEY_SYSRQ,

        // Punctuation
        "Backquote" => Key::KEY_GRAVE,
        "Minus" => Key::KEY_MINUS,
        "Equal" => Key::KEY_EQUAL,
        "BracketLeft" => Key::KEY_LEFTBRACE,
        "BracketRight" => Key::KEY_RIGHTBRACE,
        "Backslash" => Key::KEY_BACKSLASH,
        "Semicolon" => Key::KEY_SEMICOLON,
        "Quote" => Key::KEY_APOSTROPHE,
        "Comma" => Key::KEY_COMMA,
        "Period" => Key::KEY_DOT,
        "Slash" => Key::KEY_SLASH,

        // Modifiers
        "ShiftLeft" => Key::KEY_LEFTSHIFT,
        "ShiftRight" => Key::KEY_RIGHTSHIFT,
        "ControlLeft" => Key::KEY_LEFTCTRL,
        "ControlRight" => Key::KEY_RIGHTCTRL,
        "AltLeft" => Key::KEY_LEFTALT,
        "AltRight" => Key::KEY_RIGHTALT,
        "MetaLeft" => Key::KEY_LEFTMETA,
        "MetaRight" => Key::KEY_RIGHTMETA,
        "ContextMenu" => Key::KEY_COMPOSE,

        // Media / browser
        "BrowserBack" => Key::KEY_BACK,
        "BrowserForward" => Key::KEY_FORWARD,
        "BrowserRefresh" => Key::KEY_REFRESH,
        "BrowserHome" => Key::KEY_HOMEPAGE,
        "VolumeUp" => Key::KEY_VOLUMEUP,
        "VolumeDown" => Key::KEY_VOLUMEDOWN,
        "VolumeMute" => Key::KEY_MUTE,
        "MediaPlayPause" => Key::KEY_PLAYPAUSE,
        "MediaNext" => Key::KEY_NEXTSONG,
        "MediaPrev" => Key::KEY_PREVIOUSSONG,

        _ => return None,
    })
}
