import { ref } from 'vue'
import { vi } from 'vitest'
import { createDefaultConfig } from '~/types/config'

export function makeSettingsScreenMock(partial: Record<string, unknown> = {}) {
  const config = ref(createDefaultConfig())

  return {
    config,
    settingsDir: ref('/tmp/settings'),
    currentLayoutId: ref('user:test'),
    currentLayoutDescription: ref(''),
    isLayoutDirty: ref(true),
    library: {
      entries: ref([{ id: 'user:test', name: 'Test', builtin: false }]),
      error: ref(null),
      layoutsDir: ref('/tmp/layouts'),
    },
    mapper: {
      inputDevices: ref([]),
      devices: ref([]),
      mice: ref([]),
      status: ref({
        running: false,
        device_path: null,
        mouse_device_path: null,
        last_error: null,
      }),
      busy: ref(false),
      error: ref(null),
      refreshDevices: vi.fn(),
    },
    globalBanner: ref(null),
    globalIssues: ref([]),
    mapperIssues: ref([]),
    theme: {
      preference: ref('system'),
      resolved: ref('light'),
    },
    appLocale: {
      preference: ref('auto'),
      available: ['en-US', 'ru-RU'],
    },
    platform: {
      info: ref(null),
    },
    appearanceItems: ref([]),
    localeItems: ref([]),
    applying: ref(''),
    applyError: ref(null),
    pendingApply: ref(null),
    requestApplyEntry: vi.fn(),
    requestApplyEmpty: vi.fn(),
    cancelApply: vi.fn(),
    confirmApply: vi.fn(),
    saveModalOpen: ref(false),
    saveName: ref(''),
    saveBusy: ref(false),
    saveError: ref(null),
    saveCurrentLayout: vi.fn(),
    openSaveModal: vi.fn(),
    openSaveAsModal: vi.fn(),
    performSave: vi.fn(),
    closeSaveModal: vi.fn(),
    editModalOpen: ref(false),
    editName: ref(''),
    editDescription: ref(''),
    editBusy: ref(false),
    editError: ref(null),
    editPending: ref(null),
    openEditModal: vi.fn(),
    performEdit: vi.fn(),
    updateDescription: vi.fn(),
    closeEditModal: vi.fn(),
    overwriteConfirmOpen: ref(false),
    overwriteTargetName: ref(''),
    confirmOverwrite: vi.fn(),
    closeOverwriteConfirm: vi.fn(),
    resetConfirmOpen: ref(false),
    resetBusy: ref(false),
    requestReset: vi.fn(),
    confirmReset: vi.fn(),
    closeResetConfirm: vi.fn(),
    deletePending: ref(null),
    deleteBusy: ref(false),
    confirmDelete: vi.fn(),
    clearDeletePending: vi.fn(),
    deviceOptions: ref([]),
    selectedDevice: ref(''),
    mouseOptions: ref([]),
    selectedMouse: ref(''),
    toggleMapper: vi.fn(),
    ...partial,
  }
}
